SELECT * FROM
ML.PREDICT(MODEL Kaggle_Riiid.xgb_v1, (
SELECT 
user_id,
  timestamp,
  content_id,
  task_container_id,
  prior_question_elapsed_time,
  CAST(prior_question_had_explanation AS Bool) AS prior_question_had_explanation,
  CAST(n_content AS INT64) AS n_content,
  CAST(n_unique_content AS INT64) AS n_unique_content,
  CAST(user_answered_correctly_sum AS INT64) AS user_answered_correctly_sum,
  user_answered_correctly_avg,
  user_answered_correctly_std,
  CAST(user_timestamp_max AS INT64) AS user_timestamp_max,
  CAST(user_timediff_max AS INT64) AS user_timediff_max,
  CAST(user_timediff_min AS INT64) AS user_timediff_min,
  user_timediff_avg,
  user_timediff_std,
  user_prior_question_elapsed_time_max,
  user_prior_question_elapsed_time_min,
  user_prior_question_elapsed_time_avg,
  user_prior_question_elapsed_time_std,
  CAST(user_prior_question_had_explanation_sum AS INT64) AS user_prior_question_had_explanation_sum,
  user_prior_question_had_explanation_avg,
  user_prior_question_had_explanation_std,
  bundle_id,
  part,
  n_user,
  n_unique_user,
  content_answered_correctly_sum,
  content_answered_correctly_avg,
  content_answered_correctly_std,
  content_question_elapsed_time_max,
  content_question_elapsed_time_min,
  content_question_elapsed_time_avg,
  content_question_elapsed_time_std,
  CAST(content_question_had_explanation_sum AS INT64) AS content_question_had_explanation_sum,
  content_question_had_explanation_avg,
  content_question_had_explanation_std,
FROM Kaggle_Riiid.tmp_test))
